version: '3.8'
services:
  postgres-db:
    image: postgres
    container_name: user_db
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data: